name: Build Wine
on: workflow_dispatch
permissions:
  contents: read
  pull-requests: read
env:
  WINE_VERSION: "10.16"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Install dependencies'
      run: |
        echo "NAME=vinegarhq-wine-${{ env.WINE_VERSION }}" >> $GITHUB_ENV
        
    - name: 'Checkout Repository'
      uses: actions/checkout@v3

    - name: 'Fetch sources'
      run: |
        git clone https://gitlab.winehq.org/wine/wine.git --depth 1 \
          --branch wine-${{ env.WINE_VERSION }}
        git clone https://gitlab.winehq.org/wine/wine-staging.git --depth 1 \
          --branch v${{ env.WINE_VERSION }}

    - name: 'Apply patches'
      run: |
        echo "INSTALL=${{ github.workspace }}/${{ env.NAME }}" >> $GITHUB_ENV

        wine-staging/staging/patchinstall.py --destdir=wine --all
        patch -d wine -sNp1 < dont-load-bitmap-only-ttf-fonts.patch
        patch -d wine -sNp1 < xfixes-hide-cursor.patch
        patch -d wine -sNp1 < ntsync-fix-32-bit-processes.patch

    - name: 'Install build dependencies'
      run: |
        echo "PATH=/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

        sudo apt update -y
        sudo apt install \
          autoconf \
          build-essential \
          binutils \
          ccache \
          libasound2-dev \
          libdbus-1-dev \
          libfontconfig-dev \
          libfreetype-dev \
          libgl-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer1.0-dev \
          libkrb5-dev \
          libosmesa6-dev \
          libpulse-dev \
          libsdl2-dev \
          libudev-dev \
          libunwind-dev \
          libusb-1.0-0-dev \
          libv4l-dev \
          libvulkan-dev \
          libwayland-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxext-dev \
          libxfixes-dev \
          libxi-dev \
          libxinerama-dev \
          libxkbcommon-dev \
          libxkbregistry-dev \
          libxrandr-dev \
          libxrender-dev \
          mingw-w64

    - name: 'Configure ccache'
      uses: hendrikmuhs/ccache-action@v1.2

    - name: 'Configure Wine'
      working-directory: wine
      run: |
        mkdir -p ${{ env.INSTALL }}
        ./configure \
          CC='ccache gcc' \
          x86_64_CC='ccache x86_64-w64-mingw32-gcc' \
          CFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          CXXFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          CROSSCFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          --prefix=${{ env.INSTALL }} \
          --enable-win64 \
          --host=x86_64 \
          --build=x86_64 \
          --with-mingw=ccache x86_64-w64-mingw64-gcc \
          --disable-win16 \
          --disable-tests \
          --with-alsa \
          --with-pulse \
          --with-dbus \
          --with-fontconfig \
          --with-freetype \
          --with-opengl \
          --with-wayland \
          --with-x \
          --with-xcomposite \
          --with-xfixes \
          --with-xinput2 \
          --with-xrandr \
          --with-xrender \
          --with-gstreamer \
          --with-vulkan \
          --with-krb5 \
          --with-usb \
          --with-v4l2

    - name: 'Build Wine'
      working-directory: wine
      run: make -j$(($(nproc) + 1))

    - name: 'Install Wine'
      working-directory: wine
      run: make install LDCONFIG=/bin/true UPDATE_DESKTOP_DATABASE=/bin/true

    - name: 'Strip Wine DLLs'
      working-directory: ${{ env.INSTALL }}
      run: |
        x86_64-w64-mingw32-strip --strip-unneeded lib/wine/x86_64-windows/*.dll

    - name: Make artifacts
      run: |
        cd $(dirname ${{ env.INSTALL }})
        XZ_OPT=-9 tar -Jcf ${{ env.NAME }}.tar.xz $(basename ${{ env.INSTALL }})

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}
        path: ${{ env.NAME }}.tar.xz
